require("./user");
require("./category");
require("./developer");
require("./publisher");
require("./platform");
require("./systemRequirement");
require("./game");
require("./highlight");
require("./home");
